import type { Metadata } from "next";
import localFont from "next/font/local";
import Navbar from "./components/Navbar";
import "./globals.css";
import Footer from "./components/Footer";
import { AuthProvider } from "./backend/context/AuthContext";
import './css/bubble.css';

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "MPI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <AuthProvider> {/* Envolver toda la aplicación con AuthProvider */}
          <Navbar />
          <div className="bubbles"> 
            <span style={{'--i':11}as React.CSSProperties}></span>
            <span style={{'--i':12}as React.CSSProperties}></span>
            <span style={{'--i':24}as React.CSSProperties}></span>
            <span style={{'--i':10}as React.CSSProperties}></span>
            <span style={{'--i':14}as React.CSSProperties}></span>
            <span style={{'--i':23}as React.CSSProperties}></span>
            <span style={{'--i':18}as React.CSSProperties}></span>
            <span style={{'--i':16}as React.CSSProperties}></span>
            <span style={{'--i':19}as React.CSSProperties}></span>
            <span style={{'--i':20}as React.CSSProperties}></span>
            <span style={{'--i':22}as React.CSSProperties}></span>
            <span style={{'--i':25}as React.CSSProperties}></span> 
            <span style={{'--i':18}as React.CSSProperties}></span>
            <span style={{'--i':21}as React.CSSProperties}></span>
            <span style={{'--i':15}as React.CSSProperties}></span>
            <span style={{'--i':26}as React.CSSProperties}></span>
            <span style={{'--i':17}as React.CSSProperties}></span>
            <span style={{'--i':13}as React.CSSProperties}></span>
            <span style={{'--i':28}as React.CSSProperties}></span>
            <span style={{'--i':10}as React.CSSProperties}></span>
            <span style={{'--i':14}as React.CSSProperties}></span>
            <span style={{'--i':23}as React.CSSProperties}></span>
            <span style={{'--i':11}as React.CSSProperties}></span>
            <span style={{'--i':12}as React.CSSProperties}></span>
            <span style={{'--i':24}as React.CSSProperties}></span>
            <span style={{'--i':15}as React.CSSProperties}></span>
            <span style={{'--i':12}as React.CSSProperties}></span>
            <span style={{'--i':24}as React.CSSProperties}></span>
            <span style={{'--i':15}as React.CSSProperties}></span>
          </div>

          <div>{children}</div>
          <Footer />
        </AuthProvider>
      </body>
    </html>
  );
}
